### ISSUE TITLE
Hackage release roadmap

### ISSUE THREAD

**Issue by imalsogreg** [imalsogreg/servant-reflex#23]
Here are the things that need to happen before a Hackage release. 

- [x] Hackage release for `reflex-0.5` and `reflex-dom-core-0.4`
- [x] Response headers in `reflex-dom` (https://github.com/reflex-frp/reflex-dom/pull/80)
- [x] Response headers deserialized according to servant API here
- [x] Rewrite some of Req.hs to make it more readable
- [x] Finish porting the generated functions from `Behavior` to `Dynamic`
- [x] Haddock cleanup
- [x] Tests

Until then, I will keep update docs on a hackage release candidate: http://hackage.haskell.org/package/servant-reflex-0.3.3/candidate

**Comment by qrilka** [comment]
Hi @imalsogreg,
Any updates on this one?
I guess now it's mostly about cleanup and the package is in usable and stable state?

**Comment by imalsogreg** [comment]
Hey.

I'm less bothered by Req.hs than I used to be, so I'm tempted to check that one off. What do you think?

The test suite is kind of close, although I'm stuck on one test case that is commented out because I don't understand why it's failing (seems to be an issue with my use of testing framework, not the library). So I'd like to figure that out. But I'd be comfortable releasing even without a fix there just yet.

And one point that's not under a checkbox above is that I can't make a hackage release until the functor-dynamic work from reflex and some xhr stuff in reflex-dom is released on hackage. If I understand, there's some more (very fruitful!) experimentation going on there before that comes out.

**Comment by qrilka** [comment]
Ouch, I have totally missed that it works with `reflex-0.5` - wanted to try it out with our app (too much manual code) but we haven't yet migrated from `reflex-0.4`

**Comment by jappeace** [comment]
Uhm could you just release it? It's annoying that I need to create the docs manually. It works right?

**Comment by imalsogreg** [comment]
@jappeace @hvr I didn't know that release candidates have publicly available docs - that is a great solution for the moment, will do so now!

**Comment by imalsogreg** [comment]
@jappeace http://hackage.haskell.org/package/servant-reflex-0.3.3/candidate  Docs available here. I see they badly need polish.

**Comment by jappeace** [comment]
Now reflex 0.5 has been released, would you mind putting it on hackage?

**Comment by imalsogreg** [comment]
@jappeace Yes! I can't believe reflex-0.5 has been on Hackage for a month and I didn't realize. So out of the loop :)

**Comment by jappeace** [comment]
Awesome! Thanks

**Comment by imalsogreg** [comment]
http://hackage.haskell.org/package/servant-reflex-0.3.4   <-- there we go, party time!

Wow, some of the worst documentation I have ever seen :)
